/* Automatically generated by po2tbl.sed from usbview.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"USB Viewer", 2},
  {"Refresh", 3},
  {"Configure", 4},
  {"Close", 5},
  {"Couldn't find pixmap file: %s", 6},
  {"Error loading pixmap file: %s", 7},
};

int _msg_tbl_length = 7;
